### ISSUE TITLE
Update to the supported version

### ISSUE THREAD

**Issue by Chithrak07** [AcroMedia/ansible-role-wkhtmltopdf#1]
Version 0.12.5 is now archived. We will need to update to latest stable version

**Comment by dale-c-anderson** [comment]
Oof. Well, I guess the only way that would constitute a breaking change is if the CLI options to wkhtmltopdf changed.

Go ahead and update the versions. If it were a more complex role I'd be more worried about breaking stuff, but this is a really simple role that installs really simple tool. I doubt we're putting any apps at risk here. 

I'd also like to somehow turn those vars into defaults so the version can be the playbook's problem, i'll open a new issue for that.

**Comment by Chithrak07** [comment]
@dale-c-anderson : Please reivew the PR

**Comment by dale-c-anderson** [comment]
Resolved by https://github.com/AcroMedia/ansible-role-wkhtmltopdf/pull/5
